FROM node:18
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

ENV NODE_ENV=production
ENV PB_HOST=pocketbase
COPY . .
RUN npm run build

# before starting, copy all of the newly built frontend assets to the folder nginx serves
CMD node build

